
model_config:
  name: TimeDelayNNTransducer #TimeDelayTransducer/TimeDelayCTC/TimeDelayLAS
  net_scale: medium
  dropout: 0.1
  embed_dim: 64
  embed_dropout: 0.0
  num_lstms: 2
  lstm_units: 128
  joint_dim: 128
  LAS_decoder:
    n_classes: None
    embedding_hidden_size: 512
    initializer_range: 0.02
    layer_norm_eps: 1e-6
    n_prenet_layers: 2
    prenet_units: 256
    prenet_activation: "mish"
    prenet_dropout_rate: 0.5
    n_lstm_decoder: 1
    decoder_lstm_units: 256
    attention_dim: 128
    attention_filters: 32
    attention_kernel: 31
  enable_tflite_convertible: False # not support true

optimizer_config:
  learning_rate: 0.0001
  beta_1: 0.9
  beta_2: 0.98
  epsilon: 0.000001

